### PR TITLE
1.10.30 Beta

### PR DESCRIPTION
**Pull request by gir489returns**
Added Addresses for 1.10.30 Beta.

### CODE REVIEW

**Comment by ianpatt** [comment]
At a first glance this is missing quite a lot, and trying to patch on top of a WIP is hell to do. Also, there aren't plans to attempt supporting the beta versions given how unpredictably and occasionally frequently they push more.

**Comment by gir489returns** [comment]
@ianpatt What is it missing?

**Comment by ianpatt** [comment]
Memory management, all of the events, probably more. Generally it's not realistic to take external submissions of address updates, because the verification work is effectively just doing the address update again.

**Comment by gir489returns** [comment]
@ianpatt I see. I mostly did it because I opted into the beta, played for a while, then wanted to switch back but it seems I am stuck on the beta until they release the patch, whenever that might be. If you feel this isn’t applicable then I think closing the ticket would be fine.

**Pull request closed without merging**
